// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhhypbwgztoywksucvdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoaHlwYndnenRveXdrc3VjdmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjI5NzQsImV4cCI6MjA2OTk5ODk3NH0.YrGHUVfMe8Houc5G36LZvJ1BhThdo7R9b9mzgMPwBTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});